"use client";
import {useEffect,useRef,useState} from 'react';
import {Download,FileText,Search,Trash2,Upload,RotateCcw,ChevronLeft,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {api,uploadFile,fileSize} from '@/lib/client';
import {localDate} from '@/lib/defaults';
import {FileActions} from './file-library';
import {Field} from './platform';
import {toast} from 'sonner';
import ToolDownload from './tool-download';

const accept='.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.zip,.rar,.7z,.png,.jpg,.jpeg,.webp';
const emptyFilters={query:'',from:'',to:''};
type ReportItem={id:string;title:string;category:string;date:string;createdAt:string;name:string;note:string;size?:number;mime?:string;revision:number;archived?:number;legacy?:boolean;status?:string;hasPublished?:boolean};

function ReportUpload({categories,category,onDone}:any){
 const picker=useRef<HTMLInputElement>(null),[files,setFiles]=useState<File[]>([]),[type,setType]=useState('日报'),[date,setDate]=useState(localDate()),[title,setTitle]=useState(''),[note,setNote]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState('');
 function choose(){if(picker.current){picker.current.value='';picker.current.click()}}
 function selected(list:FileList|null){const next=Array.from(list||[]);if(!next.length)return;setFiles(next);setType(category==='全部报告'?categories[0]:category);setDate(localDate());setTitle('');setNote('');setError('');setOpen(true)}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!files.length)return setError('请选择报告文件。');if(!categories.includes(type))return setError('请选择报告类型。');const invalid=files.find(f=>!f.size||f.size>90*1024*1024||!accept.split(',').some(ext=>f.name.toLowerCase().endsWith(ext)));if(invalid)return setError('文件格式或大小不符合要求：'+invalid.name);setBusy(true);const done:any[]=[];
  try{for(const file of files){setProgress(`正在上传 ${done.length+1}/${files.length}：${file.name}`);done.push(await uploadFile(file,{scope:'reports',category:type,date,title:files.length===1&&title.trim()?title.trim():file.name,note}));}setOpen(false);setFiles([]);onDone(type);toast.success(`已上传 ${done.length} 份报告，可在列表删除或从回收站恢复。`)}
  catch(e:any){setError((done.length?`已有 ${done.length} 份上传成功；其余文件可重试。`:'')+e.message);if(done.length){setFiles(files.slice(done.length));onDone(type)}}finally{setBusy(false);setProgress('')}
 }
 return <><input ref={picker} type="file" accept={accept} multiple hidden aria-label="选择电脑中的报告文件" onChange={e=>selected(e.target.files)}/><Button onClick={choose}><Upload size={17}/>上传报告</Button><Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);if(!v)setFiles([])}}}><DialogContent className="upload-dialog"><DialogHeader><DialogTitle>上传报告文件</DialogTitle><DialogDescription>选择电脑中已完成的报告。上传成功后，展示账户即可查看和下载。单文件最大 90 MB。</DialogDescription></DialogHeader><form className="form-stack" onSubmit={submit}><div className="report-upload-files">{files.map((file,i)=><div key={i}><FileText size={18}/><span>{file.name}<small>{fileSize(file.size)}</small></span><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>setFiles(files.filter((_,j)=>j!==i))} aria-label={'移除 '+file.name}>移除</Button></div>)}</div><div className="form-grid"><Field label="报告类型"><select value={type} disabled={busy} onChange={e=>setType(e.target.value)}>{categories.map((x:string)=><option key={x}>{x}</option>)}</select></Field><Field label="报告日期"><Input required type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></Field></div>{files.length===1&&<Field label="报告名称（留空使用文件名）"><Input maxLength={180} value={title} disabled={busy} onChange={e=>setTitle(e.target.value)}/></Field>}<Field label="备注（选填）"><Textarea maxLength={2000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></Field>{error&&<p className="error" role="alert">{error}</p>}{progress&&<p role="status">{progress}</p>}<div className="inline-controls"><Button type="button" variant="outline" disabled={busy} onClick={()=>{setOpen(false);setFiles([])}}>取消上传</Button><Button type="submit" disabled={busy||!files.length}>{busy?'正在上传…':'确认上传'}</Button></div></form></DialogContent></Dialog></>
}

export default function ReportCenter({data}:any){
 const admin=data.user.role==='admin',generation=useRef(0);
 const [mode,setMode]=useState('active'),[category,setCategory]=useState('全部报告'),[files,setFiles]=useState<ReportItem[]>([]),[legacy,setLegacy]=useState<ReportItem[]>([]),[unpublished,setUnpublished]=useState<any[]>([]),[filters,setFilters]=useState(emptyFilters),[applied,setApplied]=useState(emptyFilters),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[loading,setLoading]=useState(true),[error,setError]=useState(''),[preview,setPreview]=useState<ReportItem|null>(null),[action,setAction]=useState<{row:ReportItem;type:string}|null>(null),[busy,setBusy]=useState(false);
 const categories=[...new Set<string>([...(data.folders.reports||['日报','周报','月报','专项报告']),...files.map(f=>f.category),'日报'])];
 const modeRef=useRef(mode);modeRef.current=mode;
 async function load(){const currentMode=modeRef.current,gen=++generation.current;setLoading(true);setError('');try{const [f,r,d]=await Promise.all([api('files?scope=reports&archived='+(currentMode==='trash'?1:0)),api('reports?status='+(currentMode==='trash'?'trash':currentMode==='legacy'?'draft':'published')),admin?api('reports?status=draft'):Promise.resolve({reports:[]})]);if(gen!==generation.current||currentMode!==modeRef.current)return;setFiles(f.files);setLegacy(r.reports.map((r:any)=>({...r,legacy:true,category:'日报',name:'',note:'',createdAt:r.updatedAt,archived:currentMode==='trash'?1:0})));setUnpublished(d.reports)}catch(e:any){if(gen===generation.current)setError(e.message)}finally{if(gen===generation.current)setLoading(false)}}
 useEffect(()=>{load();return()=>{generation.current++}},[mode,admin]);
 const items=(mode==='legacy'?legacy:[...files,...legacy]).filter(f=>(category==='全部报告'||f.category===category)&&[f.title,f.name,f.note,f.date].join(' ').toLowerCase().includes(applied.query.trim().toLowerCase())&&(!applied.from||f.date>=applied.from)&&(!applied.to||f.date<=applied.to)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 const pages=Math.max(1,Math.ceil(items.length/pageSize)),currentPage=Math.min(page,pages),visible=items.slice((currentPage-1)*pageSize,currentPage*pageSize);
 function switchMode(next:string){setMode(next);setPage(1);setCategory('全部报告');setFilters(emptyFilters);setApplied(emptyFilters)}
 async function mutateLegacy(){if(!action)return;setBusy(true);try{await api('reports/'+action.row.id,{method:'PATCH',body:JSON.stringify({action:action.type,revision:action.row.revision})});setAction(null);await load();toast.success(action.type==='trash'?'已移入回收站。':'已恢复原有存档状态。')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 const heading=mode==='trash'?'报告回收站':mode==='legacy'?'旧版未发布存档':category==='全部报告'?'报告列表':category+'列表';
 return <div className="report-center"><div className="page-heading"><div><span className="eyebrow">PROJECT REPORTS</span><h1>报告中心</h1><p>按报告类型与日期查阅工程报告。</p></div><div className="inline-controls">{admin&&<><ToolDownload filename="DailyReport-Windows-x64.zip" label="下载日报工具包"/><ReportUpload categories={categories} category={category} onDone={(type:string)=>{setCategory(type);setFilters(emptyFilters);setApplied(emptyFilters);setPage(1);if(mode!=='active')setMode('active');else load()}}/></>}</div></div>
 <section className="panel report-filter-panel"><div className="report-type-row"><Tabs value={category} onValueChange={value=>{setCategory(value);setPage(1)}}><TabsList aria-label="报告类型">{['全部报告',...categories].map(type=><TabsTrigger key={type} value={type}>{type}</TabsTrigger>)}</TabsList></Tabs>{admin&&<Button variant={mode==='trash'?'default':'outline'} onClick={()=>switchMode(mode==='trash'?'active':'trash')}><Trash2 size={16}/>{mode==='trash'?'返回报告列表':'回收站'}</Button>}</div><form className="report-search-row" onSubmit={e=>{e.preventDefault();if(filters.from&&filters.to&&filters.from>filters.to){toast.error('开始日期不能晚于结束日期。');return}setApplied({...filters});setPage(1)}}><Field label="报告名称"><Input placeholder="搜索报告名称、文件名或备注" value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})}/></Field><Field label="报告日期 · 从"><Input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></Field><Field label="报告日期 · 至"><Input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></Field><Button type="submit" variant="outline"><Search size={16}/>搜索</Button><Button type="button" variant="ghost" onClick={()=>{setFilters(emptyFilters);setApplied(emptyFilters);setCategory('全部报告');setPage(1)}}><RotateCcw size={16}/>重置</Button></form></section>
 {mode==='legacy'&&<div className="report-archive-note"><span>这些内容来自旧版在线编辑器，仅管理员可见。下载后可在电脑上完成报告，再上传到报告列表。</span><Button variant="outline" onClick={()=>switchMode('active')}>返回报告列表</Button></div>}
 <section className="panel report-list-panel" aria-label={heading} aria-busy={loading}><div className="table-toolbar"><h2>{heading}<small>{loading?'读取中…':`共 ${items.length} 份`}</small></h2><span>{mode==='trash'?'删除的报告可恢复':category}</span></div>{error?<div className="empty-state"><p className="error" role="alert">{error}</p><Button variant="outline" onClick={load}>重新加载</Button></div>:<><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>序号</TableHead><TableHead>报告名称</TableHead><TableHead>报告类型</TableHead><TableHead>报告日期</TableHead><TableHead>上传 / 存档时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{!loading&&visible.map((f,i)=><TableRow key={(f.legacy?'legacy:':'file:')+f.id}><TableCell>{(currentPage-1)*pageSize+i+1}</TableCell><TableCell><div className="report-document-name"><FileText size={21}/><div><b>{f.title}</b>{f.legacy?<small>旧版存档{mode==='legacy'?' · 未发布':''}</small>:<small>{f.name}{f.size?' · '+fileSize(f.size):''}</small>}{f.note&&<small>{f.note}</small>}</div></div></TableCell><TableCell><span className="report-type-badge">{f.category}</span></TableCell><TableCell>{f.date}</TableCell><TableCell>{f.createdAt?new Date(f.createdAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—'}</TableCell><TableCell><div className="report-row-actions">{!f.archived&&(f.legacy?<Button size="sm" variant="outline" asChild><a href={'/reports/'+f.id+(mode==='active'?'?snapshot=published':'')}>查看 / 下载</a></Button>:<><Button size="sm" variant="outline" onClick={()=>setPreview(f)}>查看报告</Button><Button size="sm" variant="ghost" asChild><a href={'/api/files/'+f.id+'?download=1'}><Download size={14}/>下载</a></Button></>)}{admin&&(f.legacy?<Button size="sm" variant="ghost" onClick={()=>setAction({row:f,type:f.archived?'restore':'trash'})}>{f.archived?'恢复':'删除'}</Button>:<FileActions file={f} folders={categories} onDone={load}/>)}</div></TableCell></TableRow>)}</TableBody></Table></div>{loading?<p className="empty-state" role="status">正在读取报告…</p>:!items.length&&<div className="empty-state"><FileText size={32}/><h3>{mode==='trash'?'回收站暂无报告':'暂无符合条件的报告'}</h3><p>{mode==='trash'?'删除的报告会显示在这里。':admin?'可调整筛选条件，或点击“上传报告”选择电脑中的文件。':'可调整筛选条件，或等待管理员上传。'}</p></div>}<div className="report-pagination"><span>共 {items.length} 份报告</span><select aria-label="每页报告数量" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[10,20,50].map(n=><option key={n} value={n}>{n} 条/页</option>)}</select><Button size="sm" variant="outline" disabled={currentPage===1||loading} onClick={()=>setPage(currentPage-1)} aria-label="上一页"><ChevronLeft size={16}/></Button><span>{currentPage} / {pages}</span><Button size="sm" variant="outline" disabled={currentPage===pages||loading} onClick={()=>setPage(currentPage+1)} aria-label="下一页"><ChevronRight size={16}/></Button></div></>}</section>
 {admin&&mode!=='legacy'&&unpublished.length>0&&<div className="report-legacy-link"><Button variant="ghost" onClick={()=>switchMode('legacy')}>旧版未发布存档（{unpublished.length}）</Button></div>}
 <Dialog open={!!preview} onOpenChange={v=>!v&&setPreview(null)}><DialogContent className="preview-dialog"><DialogHeader><DialogTitle>{preview?.title}</DialogTitle><DialogDescription>{preview?.category} · {preview?.date} · {preview?.name}</DialogDescription></DialogHeader>{preview&&(preview.mime==='application/pdf'?<iframe className="pdf-preview" src={'/api/files/'+preview.id} title={preview.title}/>:preview.mime?.startsWith('image/')?<img className="file-image-preview" src={'/api/files/'+preview.id} alt={preview.title}/>:<div className="empty-state"><FileText size={34}/><p>此格式请下载后使用电脑上的对应软件查看。</p></div>)}<Button asChild><a href={'/api/files/'+preview?.id+'?download=1'}><Download size={16}/>下载报告</a></Button></DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction(null)}}><DialogContent><DialogHeader><DialogTitle>{action?.type==='trash'?'删除报告至回收站':'恢复报告存档'}</DialogTitle><DialogDescription>{action?.type==='trash'?'删除后展示账户无法再查看，可在回收站恢复。':'恢复原有状态：已发布内容返回报告列表，未发布内容仅管理账户可见。'}</DialogDescription></DialogHeader><p>{action?.row.title}</p><div className="inline-controls"><Button variant="outline" disabled={busy} onClick={()=>setAction(null)}>取消</Button><Button disabled={busy} onClick={mutateLegacy}>确认{action?.type==='trash'?'删除':'恢复'}</Button></div></DialogContent></Dialog>
 </div>
}
