"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {api} from '@/lib/client';
import {runs} from '@/lib/reports';
import {planGallery,galleryImages,stablePath} from '@/lib/report-layout';
import {exportDocx} from '@/lib/report-export';
import {toast} from 'sonner';
export function GalleryPreview({r,path}:any){const p=stablePath(r,path),images=galleryImages(r,p),[dims,setDims]=useState<Record<string,any>>({});useEffect(()=>{let live=true;Promise.all(images.map(im=>new Promise<any>(resolve=>{const image=new Image();image.onload=()=>resolve([im.id,{width:image.naturalWidth,height:image.naturalHeight}]);image.onerror=()=>resolve([im.id,{width:im.width||4,height:im.height||3}]);image.src='/api/files/'+im.id}))).then(items=>{if(live)setDims(Object.fromEntries(items))});return()=>{live=false}},[images.map(x=>x.id).join('|')]);let rows:any[]=[];try{rows=planGallery(r,p,p.endsWith('.photos')?175:415,dims)}catch(e:any){return <p className="error">{e.message}</p>}return <div className="planned-gallery" style={{width:(p.endsWith('.photos')?175:415)+'pt',maxWidth:'100%'}}>{rows.map((row,i)=><div key={i} className={'planned-row '+(row.breakBefore?'page-before ':'')+(row.breakAfter?'page-after':'')} style={{gridTemplateColumns:`repeat(${row.columns},minmax(0,1fr))`,gap:row.gapPt+'pt'}}>{row.items.map((item:any)=><figure key={item.id} style={{gridColumn:`${item.column+1} / span ${item.span}`,textAlign:item.align}}><img src={'/api/files/'+item.id} alt={item.caption||'现场照片'} style={{width:item.widthPt+'pt',maxWidth:'100%',aspectRatio:item.widthPt/item.heightPt,objectFit:'contain',display:'inline-block'}}/>{item.caption&&<figcaption style={{whiteSpace:'pre-wrap'}}>{item.caption}</figcaption>}{item.ownPage&&<small className="layout-page-label">独占一页</small>}</figure>)}</div>)}</div>}

function RichParagraph({ r, path }: any) { return <p className={'report-paragraph ' + (path.startsWith('heading.') ? 'report-heading' : '')}>{runs(r, path).map((x: any, i: number) => <span key={i} style={{ color: '#' + (x.color || '000000'), fontWeight: x.bold ? 700 : 400, fontSize:(x.size||14)+'pt', fontStyle: x.italic ? 'italic' : 'normal', textDecoration: x.underline ? 'underline' : 'none', whiteSpace: 'pre-wrap' }}>{x.text}</span>)}</p>; }
export function ReportPreview({ r, status }: any) { return <article className="report-paper"><div className="report-letterhead"><img src="/api/assets/report-logo.png" alt="项目标志"/><span>{status === 'published' ? '已归档报告' : '旧版未发布存档'}</span></div><h1>{r.project}</h1><h2>{r.title}</h2><div className="report-number">编号：{r.number}</div><table className="report-meta"><tbody><tr><th>工作日期</th><td>{r.date}</td><th>天气</th><td>{r.weather || '—'}</td></tr><tr><th>顾问专家</th><td>{r.experts || '—'}</td><th>施工任务</th><td>{r.slots.task || '—'}</td></tr></tbody></table><RichParagraph r={r} path="heading.demolition"/><RichParagraph r={r} path="heading.demolition_overview"/><RichParagraph r={r} path="demolition.overview"/><RichParagraph r={r} path="demolition.focus"/><GalleryPreview r={r} path="demolition.images"/>{r.demolition.issuesEnabled && <><RichParagraph r={r} path="heading.issues"/><table className="report-table"><thead><tr><th>序号</th><th>现场图片</th><th>顾问关注事项</th></tr></thead><tbody>{r.demolition.issues.length ? r.demolition.issues.map((x: any, i: number) => <tr key={x.id}><td>{i + 1}</td><td><GalleryPreview r={r} path={"demolition.issues."+x.id+".photos"}/></td><td>{x.advice || '—'}</td></tr>) : <tr><td colSpan={3}>本项未填写</td></tr>}</tbody></table></>}<RichParagraph r={r} path="demolition.conclusion"/><RichParagraph r={r} path="heading.drainage"/><RichParagraph r={r} path="heading.drainage_overview"/><RichParagraph r={r} path="drainage.overview"/><GalleryPreview r={r} path="drainage.images"/><RichParagraph r={r} path="heading.drainage_safety"/><table className="report-table"><thead><tr><th>序号</th><th>现场安全事项</th><th>顾问关注事项</th></tr></thead><tbody>{r.drainage.items.map((x: any, i: number) => <tr key={x.id}><td>{i + 1}</td><td>{x.item}</td><td>{x.advice || '—'}</td></tr>)}</tbody></table><RichParagraph r={r} path="drainage.conclusion"/><GalleryPreview r={r} path="drainage.monitoring"/><RichParagraph r={r} path="heading.plans"/><table className="report-table"><thead><tr><th>序号</th><th>计划事项</th></tr></thead><tbody>{r.plans.length ? r.plans.map((x: any, i: number) => <tr key={x.id}><td>{i + 1}</td><td>{x.text}</td></tr>) : <tr><td colSpan={2}>本项未填写</td></tr>}</tbody></table><div className="report-signatures"><p>编制：{r.signatures.authors || '—'}</p><p>复核：{r.signatures.reviewers || '—'}</p><p>批准：{r.signatures.approver || '—'}</p></div></article>; }

export default function ReportArchive({id}:any){
 const [record,setRecord]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;const snapshot=new URLSearchParams(location.search).get('snapshot');api('reports/'+id+(snapshot==='published'?'?snapshot=published':'')).then(b=>{if(live)setRecord(b)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[id]);
 return <div className="report-workspace"><div className="report-toolbar"><a href="/reports">← 返回报告中心</a><div><h1>旧版报告存档</h1><span>保留原有内容，可下载后在电脑上修改，再上传报告文件。</span></div>{record&&<div className="report-actions"><Button disabled={busy} onClick={async()=>{setBusy(true);try{await exportDocx(record.report,record.status)}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>{busy?'正在准备…':'下载 Word'}</Button><Button variant="outline" onClick={()=>window.print()}>打印 / 保存 PDF</Button></div>}</div>{error?<p className="error">{error}</p>:record?<ReportPreview r={record.report} status={record.status}/>:<p className="empty-state">正在读取存档…</p>}</div>
}
