"use client";
import ChangeHistory from "@/app/change-history";
import {api} from "@/lib/client";
import {appConfig,appFetch,appUrl} from "@/lib/app-runtime";
import {useEffect,useState} from "react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Upload,Download,Save,Plus,Trash2,Droplets,ArrowUpRight,RotateCw} from "lucide-react";
import type {Monitoring,CellEdit} from "@/lib/model";
import {validDate,mergeEdits,deletionEdits} from "@/lib/model";
import {parseWorkbook,exportCSV} from "@/lib/workbook-import";
import map from "@/data/map.json";
const ids=map.points.map(p=>p.id);
type Preview={edits:CellEdit[];name:string};
type Deletion={revision:number;edits:CellEdit[];dates:string[];wholeRows:boolean;points:string[]};
export default function Admin(){
 const [data,setData]=useState<Monitoring|null>(null),[edits,setEdits]=useState<Record<string,string>>({}),[newDates,setNewDates]=useState<string[]>([]);
 const [newDate,setNewDate]=useState(""),[filter,setFilter]=useState("all"),[message,setMessage]=useState(""),[isError,setIsError]=useState(false),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[pendingSection,setPendingSection]=useState<{id:string;file:File;url:string;expectedVersion:string;replacing:boolean}|null>(null);
 const [selectedDates,setSelectedDates]=useState<string[]>([]),[deletion,setDeletion]=useState<Deletion|null>(null);
 const tell=(s:string,error=false)=>{setMessage(s);setIsError(error);};
 const load=async()=>{try{const r=await appFetch("/api/monitoring",{cache:"no-store"});const v=await r.json() as Monitoring & {error?:string;url:string};if(!r.ok)throw Error(v.error||"操作失败");setData(v);}catch(e){tell(e instanceof Error?e.message:"读取失败",true);}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(Object.keys(edits).length||preview){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",f);return()=>window.removeEventListener("beforeunload",f);},[edits,preview]);
 const changed=Object.keys(edits).length;
 const dates=[...new Set([...(data?Object.keys(data.records):[]),...newDates])].sort().reverse();
 const visible=ids.filter(id=>filter==="all"||filter==="SW"&&id.startsWith("SW")||filter==="NSW"&&id.startsWith("NSW")||filter==="faulty"&&data?.faulty.includes(id)||filter===id);
 const makeEdits=():CellEdit[]=>Object.entries(edits).map(([k,v])=>{const [date,id]=k.split("|");if(v.trim()!==""&&!Number.isFinite(Number(v)))throw Error(date.replace("T"," ")+" "+id+" 不是数值。");return {date,id,value:v.trim()===""?null:Number(v)};});
 const save=async(incoming?:CellEdit[],expectedRevision=data?.revision)=>{
   if(!data)return false;setBusy(true);
   try{
     if(expectedRevision!==data.revision)throw Error("数据已变化，请取消后重新核对所选记录。");
     const patch=incoming||makeEdits();mergeEdits(data.records,patch,ids);
     const r=await appFetch("/api/monitoring",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:expectedRevision,edits:patch})});const v=await r.json() as Monitoring & {error?:string;url:string};if(!r.ok)throw Error(v.error||"操作失败");
     setData(v);setEdits({});setNewDates([]);setPreview(null);tell("已保存。展示页会在 15 秒内自动读取；无需重新发布平台。");return true;
   }catch(e){tell(e instanceof Error?e.message:"保存失败。",true);return false;}finally{setBusy(false);}
 };
 const requestDeletion=(wholeRows:boolean)=>{
   if(!data||changed||busy||preview)return;
   const patch=deletionEdits(data.records,selectedDates,visible,wholeRows);
   if(!patch.length){tell("所选时刻没有这些测点的数据，无需删除。");return;}
   tell("");setDeletion({revision:data.revision,edits:patch,dates:[...selectedDates].sort(),wholeRows,points:[...visible]});
 };
 const confirmDeletion=async()=>{if(deletion&&await save(deletion.edits,deletion.revision)){setDeletion(null);setSelectedDates([]);tell("所选历史数据已删除，观测图表将在 15 秒内更新。");}};
 const add=()=>{if(!validDate(newDate)){tell("请选择完整的观测日期和时刻。",true);return;}if(dates.includes(newDate)){tell("该时刻已经存在，请直接在表格中编辑。",true);return;}setNewDates(v=>[...v,newDate]);tell("已加入 "+newDate.replace("T"," ")+"。请填写坑内液面和本次有观测的测点。");};
 const importFile=async(file:File)=>{
   if(changed){tell("请先保存当前表格的修改，再导入文件。",true);return;}
   setBusy(true);try{const parsed=await parseWorkbook(file,ids);const actual=parsed.edits.filter(e=>{const old=data?.records[e.date]?.[e.id];return old===undefined||e.value===null||Math.abs(old-e.value)>1e-9;});if(!actual.length){tell("该文件与现有数据一致，没有需要保存的修改。");return;}if(data)mergeEdits(data.records,actual,ids);setPreview({...parsed,edits:actual});tell("文件已读取，请检查导入预览后保存。");}catch(e){tell(e instanceof Error?e.message:"文件读取失败。",true);}finally{setBusy(false);}
 };
 const uploadSection=async()=>{
   if(!pendingSection)return;setBusy(true);const pending=pendingSection;
   try{const f=new FormData();f.append("file",pending.file);f.append("expectedVersion",pending.expectedVersion);const r=await appFetch("/api/sections/"+encodeURIComponent(pending.id),{method:"POST",body:f});const v=await r.json() as {error?:string;url:string;version:string};if(!r.ok)throw Error(v.error||"操作失败");setData(d=>d?{...d,sections:{...d.sections,[pending.id]:v.url},sectionVersions:{...d.sectionVersions,[pending.id]:v.version}}:d);tell("断面图片已保存，观测页面将在 15 秒内显示新图。");URL.revokeObjectURL(pending.url);setPendingSection(null);}catch(e){tell(e instanceof Error?e.message:"上传失败。",true);}finally{setBusy(false);}
 };
 return <div className="admin-app">
 <main className="admin-main"><div className="admin-heading"><div><h1>监测数据维护</h1><p>填写观测时间与水位，保存后同步到平面图。</p></div><div className="admin-nav"><ChangeHistory target="monitor" version={async()=>(await api("monitoring")).revision} onDone={()=>{setEdits({});setNewDates([]);setPreview(null);setSelectedDates([]);load()}}/><button className="admin-button" disabled={!!changed||busy||!!preview} onClick={load}><RotateCw size={15}/>重新载入</button></div></div>
 <Tabs defaultValue="water"><TabsList><TabsTrigger value="water">水位数据</TabsTrigger><TabsTrigger value="sections">断面图片</TabsTrigger><TabsTrigger value="help">维护说明</TabsTrigger></TabsList>
 {message&&<div className={"admin-message "+(isError?"error":"")} role="status">{message}</div>}
 <TabsContent value="water"><section className="admin-card"><h2>观测数据表</h2><p>每行是一个观测时刻。坑内液面只填一次，所有 SW、NSW 曲线按该时刻共用。数值单位为 m，使用换算标高。</p>
 <div className="admin-controls"><label>观测时间<input type="datetime-local" step="60" value={newDate} onChange={e=>setNewDate(e.target.value)}/></label><button className="admin-button" onClick={add} disabled={!data||busy||!!preview}><Plus size={15}/>增加一行</button><label>显示<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部测点</option><option value="SW">SW</option><option value="NSW">NSW</option><option value="faulty">原表故障点</option><optgroup label="单个测点">{ids.map(id=><option key={id} value={id}>{id}</option>)}</optgroup></select></label><span className="save-hint">{changed?changed+" 个单元格待保存":"时间按新到旧排列"}</span><button className="admin-button primary" disabled={!changed||busy||!!preview} onClick={()=>save()}><Save size={16}/>{busy?"保存中…":"保存修改"}</button></div>
 <div className="admin-controls"><label className="admin-button"><Upload size={16}/>导入 Excel / CSV<input type="file" accept=".xlsx,.csv" disabled={busy||!!preview} style={{display:"none"}} onChange={e=>{if(e.target.files?.[0])importFile(e.target.files[0]);e.target.value="";}}/></label><button className="admin-button" disabled={!data||!!changed} onClick={()=>data&&exportCSV(data.records,ids)}><Download size={16}/>导出数据表</button><a href={appUrl("/assets/source.xlsx")} download className="admin-button">下载原始 Excel</a></div>
 <div className="admin-controls history-controls"><span>{selectedDates.length?"已选 "+selectedDates.length+" 个观测时刻":"勾选左侧观测时刻，可删除历史数据"}</span><button className="admin-button danger-button" disabled={!selectedDates.length||!!changed||busy||!!preview} onClick={()=>requestDeletion(false)}><Trash2 size={15}/>删除所选测点数据</button><button className="admin-button danger-button" disabled={!selectedDates.length||!!changed||busy||!!preview} onClick={()=>requestDeletion(true)}>删除所选整行</button>{!!selectedDates.length&&<button className="admin-button" onClick={()=>setSelectedDates([])} disabled={busy}>取消勾选</button>}{(!!changed||newDates.length>0)&&<button className="admin-button" onClick={()=>{setEdits({});setNewDates([]);setPreview(null);setSelectedDates([]);tell("已撤销尚未保存的单元格修改。");}} disabled={busy}>撤销未保存修改</button>}</div>
 {preview&&<div className="import-preview"><h3>导入预览 · {preview.name}</h3><p>{preview.edits.length} 个观测值，{new Set(preview.edits.map(e=>e.date)).size} 个时刻。空白单元格保留原记录。</p><p>时间范围：{preview.edits.map(e=>e.date).sort()[0].replace("T"," ")} 至 {preview.edits.map(e=>e.date).sort().at(-1)?.replace("T"," ")}</p><p>涉及：{[...new Set(preview.edits.map(e=>e.id==="PIT"?"坑内液面":e.id))].join("、")}</p><div className="grid-shell" style={{maxHeight:200,marginTop:12}}><Table><TableHeader><TableRow><TableHead>时间</TableHead><TableHead>测点</TableHead><TableHead>原值</TableHead><TableHead>导入值</TableHead></TableRow></TableHeader><TableBody>{preview.edits.slice(0,100).map(e=><TableRow key={e.date+e.id}><TableCell>{e.date.replace("T"," ")}</TableCell><TableCell>{e.id}</TableCell><TableCell>{data?.records[e.date]?.[e.id]??"—"}</TableCell><TableCell>{e.value}</TableCell></TableRow>)}</TableBody></Table></div>{preview.edits.length>100&&<p>预览前 100 个修改，确认后保存全部 {preview.edits.length} 个。</p>}<div className="import-buttons"><button className="admin-button primary" onClick={()=>save(preview.edits)} disabled={busy}>确认并保存</button><button className="admin-button" onClick={()=>setPreview(null)} disabled={busy}>取消导入</button></div></div>}
 <div className="grid-shell"><table className="data-grid"><thead><tr><th><label className="history-date"><input type="checkbox" aria-label="选择全部已有观测时刻" checked={!!data&&Object.keys(data.records).length>0&&Object.keys(data.records).every(d=>selectedDates.includes(d))} disabled={!data||busy||!!preview} onChange={e=>setSelectedDates(e.target.checked?Object.keys(data?.records||{}):[])}/>观测时间</label></th><th className="pit-col">坑内液面 / m</th>{visible.map(id=><th key={id} className={data?.faulty.includes(id)?"faulty-col":""}>{id}</th>)}</tr></thead><tbody>{dates.map(date=><tr key={date} className={newDates.includes(date)?"new-row":""}><td><label className="history-date"><input type="checkbox" aria-label={"选择 "+date.replace("T"," ")} checked={selectedDates.includes(date)} disabled={!data?.records[date]||busy||!!preview} onChange={e=>setSelectedDates(v=>e.target.checked?[...v,date]:v.filter(d=>d!==date))}/>{date.replace("T"," ")}</label></td>{["PIT",...visible].map(id=>{const key=date+"|"+id;const dirty=key in edits;return <td key={id} className={dirty?"edited-cell":id==="PIT"?"pit-col":data?.faulty.includes(id)?"faulty-col":""}><input type="text" inputMode="decimal" aria-label={date+" "+id} disabled={busy||!!preview} value={dirty?edits[key]:data?.records[date]?.[id]??""} onChange={e=>{const v=e.target.value;setEdits(old=>{const n={...old};if(v===String(data?.records[date]?.[id]??""))delete n[key];else n[key]=v;return n;});}}/></td>;})}</tr>)}</tbody></table></div>
 {!data&&<p>正在读取观测数据…</p>}<div className="admin-note"><strong>黄色列：{data?.faulty.join("、")||"—"}</strong>，对应原表故障点。保留历史记录；换新后可继续填写。蓝色单元格为尚未保存的修改。<br/>时间沿用原表本地工程时刻；原表只有日期的记录按 00:00 保存，未推定额外观测时刻。</div>
 </section></TabsContent>
 <TabsContent value="sections"><section className="admin-card"><h2>断面图片维护</h2><p>每个断面都可上传或替换图片，包括 4-4 与 5-5。先预览并核对编号，再确认保存；观测页面会自动显示新图。</p><div className="section-grid">{map.sections.map(s=><div className="section-card" key={s.id}><b>{s.label}</b><div className="section-actions"><ChangeHistory kind="section" target={s.id} version={async()=>(await api("monitoring")).sectionVersions[s.id]||"empty"} onDone={load}/>{data?.sections[s.id]&&<button className="admin-button" disabled={busy} onClick={async()=>{if(!window.confirm("删除此断面图？可在修改记录中恢复。"))return;try{await api("sections/"+s.id,{method:"PATCH",body:JSON.stringify({action:"trash",expectedVersion:data.sectionVersions?.[s.id]||"original"})});load()}catch(e:any){tell(e.message,true)}}}>删除图片</button>}{data?.sections[s.id]&&<a href={appUrl(data.sections[s.id])} target="_blank" rel="noreferrer">查看当前图片</a>}<label>{data?.sections[s.id]?"替换图片":"上传图片"}<input type="file" accept="image/png,image/jpeg" disabled={!data||busy} onChange={e=>{const file=e.target.files?.[0];if(file){if(file.size>10*1024*1024){tell("图片须小于 10 MB。",true);}else {tell("");setPendingSection({id:s.id,file,url:URL.createObjectURL(file),expectedVersion:data?.sectionVersions?.[s.id]||(data?.sections[s.id]?"original":"empty"),replacing:!!data?.sections[s.id]});}}e.target.value="";}}/></label></div></div>)}</div></section></TabsContent>
 <TabsContent value="help"><section className="admin-card"><h2>日常维护</h2><p><strong>直接填表：</strong>选好日期和时刻，增加一行，填写同一时刻的坑内液面与有观测的 SW / NSW，点击“保存修改”。没有观测的数据留空。现有记录也可直接校正，清空后保存会移除该单元格数值。</p><p><strong>删除历史数据：</strong>勾选观测时刻，在“显示”中选择全部、SW、NSW 或单个测点，再点“删除所选测点数据”，仅删除这些测点的值，保留坑内液面及其他测点。“删除所选整行”会删除该时刻全部测点和坑内液面，不受显示筛选影响。核对确认框后提交；单个数值也可清空后保存。</p><p><strong>使用 Excel：</strong>点击“导出数据表”，用 Excel 打开 CSV，保持“时间、坑内液面、SW1…NSW11”列名，新增时间行。保存为 UTF-8 CSV 或 XLSX，然后在此导入。先检查预览，再确认保存。</p><p><strong>使用原始 Excel：</strong>可继续在“地下水位曲线 (换算标高曲线)”中向右新增时间列；第 1 行为日期时间，第 2 行为坑内液面，第 3–19 行依次为 SW1–SW17。导入时仅读取换算标高表。NSW 请在本后台表格或带列名的导出表中填写，不要在无标签的原表底部自行加行。</p><p><strong>更新节奏：</strong>保存写入后，打开的展示页每 15 秒自动读取一次。在电脑上的 Excel 中修改文件后，需要导入此后台才会同步；本平台不会自行读取电脑上的文件。</p><p><strong>故障测点：</strong>原表黄色对应 {data?.faulty.join("、")}。不补零、不延长缺测线段。更换设备后继续使用原编号填入新记录；如恢复测量的具体时间未记录，不能据此推定。</p><p><strong>断面：</strong>进入“断面图片”，上传或替换对应编号的图片，预览核对后保存。如果其他窗口同时改过该图片，需重新载入后再确认。</p><p><strong>访问：</strong>{appConfig().audience==="local-admin"?"本机后台由文件夹中的“02-启动后台数据管理”快捷方式直接打开，无需密码；“01-打开观测平台”仅供观测。":"观测用户只读，管理员登录后可维护水位和断面图片。"}</p></section><section className="admin-card"><h2>原始资料与校核</h2><p>水位来源：{data?.source}。底图：俯瞰平面图.png；初始断面：4-4断面.png、5-5断面.png。</p>{data?.warnings?.map((w,i)=><p key={i}>{w}</p>)}<div className="admin-links"><a href={appUrl("/assets/source.xlsx")} download>原始监测表</a><a href={appUrl("/assets/plan.png")} target="_blank" rel="noreferrer">原始平面图</a></div><p className="footer-sources">实现参考：<a href="https://developers.cloudflare.com/d1/worker-api/d1-database/" target="_blank" rel="noreferrer">数据持久化文档</a> · <a href="https://developers.cloudflare.com/r2/api/workers/workers-api-reference/" target="_blank" rel="noreferrer">断面条件写入文档</a></p></section></TabsContent>
 </Tabs></main>
 <AlertDialog open={!!pendingSection} onOpenChange={v=>{if(!v&&!busy&&pendingSection){URL.revokeObjectURL(pendingSection.url);setPendingSection(null);}}}><AlertDialogContent className="max-w-2xl"><AlertDialogHeader><AlertDialogTitle>{pendingSection?.replacing?"替换":"上传"} {map.sections.find(s=>s.id===pendingSection?.id)?.label} 断面</AlertDialogTitle><AlertDialogDescription>{pendingSection?.replacing?"请核对新图与断面编号。确认后，观测页面将显示这张新图。":"请核对图纸与断面编号，确认后上传。"}</AlertDialogDescription></AlertDialogHeader>{pendingSection&&<img src={pendingSection.url} alt="待保存断面预览" className="section-review-image"/>}{isError&&<p role="alert" className="admin-message error">{message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>返回检查</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();uploadSection();}}>{busy?"保存中…":pendingSection?.replacing?"确认替换图片":"确认上传图片"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!deletion} onOpenChange={v=>{if(!v&&!busy)setDeletion(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{deletion?.wholeRows?"删除所选整行？":"删除所选测点数据？"}</AlertDialogTitle><AlertDialogDescription>{deletion?.wholeRows?"将删除所选时刻的全部 SW、NSW 和坑内液面，包括当前未显示的列。":"将删除所选时刻中指定测点的数值，坑内液面及其他测点保持不变。"}</AlertDialogDescription></AlertDialogHeader>{deletion&&<div className="deletion-details"><p>{deletion.dates.length} 个观测时刻，共 {deletion.edits.length} 个数值。</p>{!deletion.wholeRows&&<p>测点：{deletion.points.join("、")}</p>}<ul>{deletion.dates.slice(0,8).map(date=><li key={date}>{date.replace("T"," ")}</li>)}</ul>{deletion.dates.length>8&&<p>另有 {deletion.dates.length-8} 个所选时刻。</p>}</div>}{isError&&<p role="alert" className="admin-message error">{message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction className="danger-button" disabled={busy} onClick={e=>{e.preventDefault();confirmDeletion();}}>{busy?"删除中…":"确认删除"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}

