import {db,HttpError,iso,json,readJSON} from './auth';
import {initialProject,initialFolders,type User} from './defaults';
import seed from '@/data/seed.json';
const defaults:Record<string,any>={project:initialProject,folders:initialFolders,monitor:seed.records};
export async function getSetting(key:string,fallback:any=defaults[key]){const r=await db().prepare('SELECT payload,revision FROM settings WHERE key=?').bind(key).first<any>();return {value:r?JSON.parse(r.payload):fallback,revision:r?.revision||0};}
export function historyStatement(kind:string,target:string,before:any,version:string|number,action:string,user:User){return db().prepare('INSERT INTO change_history(id,kind,target,before_payload,after_version,action,username,created_at) SELECT ?,?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),kind,target,JSON.stringify(before??null),String(version),action,user.username,iso());}
export async function commitSetting(key:string,value:any,revision:number,user:User,action='保存修改'){const old=await getSetting(key);if(!Number.isInteger(revision)||revision!==old.revision)throw new HttpError(409,'内容已有更新，请重新载入。');const q=revision===0?db().prepare('INSERT INTO settings(key,payload,revision,updated_at) VALUES(?,?,1,?) ON CONFLICT(key) DO NOTHING RETURNING revision').bind(key,JSON.stringify(value),iso()):db().prepare('UPDATE settings SET payload=?,revision=revision+1,updated_at=? WHERE key=? AND revision=? RETURNING revision').bind(JSON.stringify(value),iso(),key,revision);const result=await db().batch([q,historyStatement('setting',key,old.value,revision+1,action,user)]);if(!result[0].results?.length)throw new HttpError(409,'内容已在另一个窗口更新，请重新载入。');return revision+1;}
export function sectionVersion(row:any,id:string){return row?(row.archived?'deleted:':'')+row.object_key:(['4','5'].includes(id)?'original':'empty');}
export async function changeHistoryAPI(request:Request,parts:string[],user:User){if(user.role!=='admin')throw new HttpError(403,'仅管理账户可访问修改记录。');if(request.method==='GET'){const url=new URL(request.url),kind=url.searchParams.get('kind'),target=url.searchParams.get('target');const clauses:string[]=["NOT (kind='setting' AND target='ai')"],bind:any[]=[];if(kind){clauses.push('kind=?');bind.push(kind)}if(target){clauses.push('target=?');bind.push(target)}const rows=await db().prepare('SELECT id,kind,target,after_version AS afterVersion,action,username,created_at AS createdAt FROM change_history'+(clauses.length?' WHERE '+clauses.join(' AND '):'')+' ORDER BY created_at DESC LIMIT 100').bind(...bind).all();return json({changes:rows.results});}
 if(request.method!=='POST'||parts[2]!=='restore')throw new HttpError(404,'操作不存在。');const row=await db().prepare('SELECT * FROM change_history WHERE id=?').bind(parts[1]).first<any>();if(!row)throw new HttpError(404,'记录不存在。');const b=await readJSON(request),before=JSON.parse(row.before_payload);
 if(row.kind==='setting'){if(row.target==='ai')throw new HttpError(410,'网站内 AI 已移除，不能恢复配置。');if(row.target==='folders'){const currentFolders=await getSetting('folders');for(const scope of ['documents','simulation','reports']){for(const category of currentFolders.value[scope]||[]){if(!before[scope]?.includes(category)){const used=await db().prepare('SELECT id FROM files WHERE scope=? AND category=? LIMIT 1').bind(scope,category).first();if(used)throw new HttpError(409,'该历史分类方案缺少已有文件的分类，请先移动文件。');}}}}const current=await getSetting(row.target);if(String(b.expectedVersion)!==String(current.revision))throw new HttpError(409,'已出现新的修改，请刷新记录后重试。');const revision=await commitSetting(row.target,before,current.revision,user,'恢复修改前版本');return json({revision});}
 if(row.kind==='file'){const current=await db().prepare('SELECT * FROM files WHERE id=?').bind(row.target).first<any>();if(!current||String(current.revision)!==String(b.expectedVersion))throw new HttpError(409,'文件已有更新，请刷新。');if(current.scope==='report-image')throw new HttpError(410,'旧版报告附件为只读存档。');if(before.archived&&current.scope==='report-image'){const report=await db().prepare('SELECT * FROM reports WHERE id=? AND deleted_at IS NULL').bind(current.category).first<any>();const payload=report&&(report.published_payload||(report.status==='published'?report.payload:null));if(payload){const p=JSON.parse(payload);if([...(p.demolition.images||[]),...(p.demolition.issues||[]).flatMap((x:any)=>x.photos||[]),...(p.drainage.images||[]),...(p.drainage.monitoring||[])].some(x=>x.id===current.id))throw new HttpError(409,'历史恢复会移除正式日报仍在使用的图片，请先撤回正式日报。');}}const revision=current.revision+1;const result=await db().batch([db().prepare('UPDATE files SET title=?,category=?,date=?,note=?,archived=?,revision=revision+1 WHERE id=? AND revision=? RETURNING revision').bind(before.title,before.category,before.date,before.note,before.archived,row.target,current.revision),historyStatement('file',row.target,current,revision,'撤回文件修改',user)]);if(!result[0].results.length)throw new HttpError(409,'文件已有更新。');return json({revision});}
 if(row.kind==='section'){const current=await db().prepare('SELECT * FROM section_archives WHERE id=?').bind(row.target).first<any>();if(sectionVersion(current,row.target)!==b.expectedVersion)throw new HttpError(409,'断面图已有更新，请刷新。');const key=before?.object_key||'original:'+row.target,archived=before?.archived??(['4','5'].includes(row.target)?0:1);const statement=current?db().prepare('UPDATE section_archives SET object_key=?,archived=?,created_at=? WHERE id=? AND object_key=? AND archived=? RETURNING id').bind(key,archived,iso(),row.target,current.object_key,current.archived):db().prepare('INSERT INTO section_archives(id,object_key,archived,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING RETURNING id').bind(row.target,key,archived,iso());const result=await db().batch([statement,historyStatement('section',row.target,current,(archived?'deleted:':'')+key,'恢复断面图',user)]);if(!result[0].results.length)throw new HttpError(409,'断面图已有更新。');return json({version:(archived?'deleted:':'')+key});}
 throw new HttpError(400,'此类内容请在对应模块的修订记录中恢复。');}
