import {validateLayout} from './report-layout';
import template from '@/data/report-template.json';
export const stages=[['basics','基本信息'],['demolition','拆除作业'],['issues','结构安全意见'],['drainage','降排水作业'],['drainage_safety','降排水安全意见'],['plans','次日计划'],['signatures','编制与复核']];
export const reportTemplate=template;
export function reportNumber(date:string){const n=Math.floor((Date.parse(date+'T00:00:00Z')-Date.parse('2026-08-12T00:00:00Z'))/86400000)+1;return 'GZRB-'+date.slice(0,4)+'-'+(n>0?String(n).padStart(4,'0'):date.replaceAll('-',''));}
export function newReport(date:string,project:any){return {id:crypto.randomUUID(),date,number:reportNumber(date),title:'结构安全顾问工作日报',project:project.fullName||project.name,weather:'',experts:'',slots:{task:'',work:'',inspection:'',completed:'',water_level:'',water_change:''},rich:JSON.parse(JSON.stringify(template.fragments)),demolition:{images:[],issuesEnabled:true,issues:[]},drainage:{images:[],monitoring:[],items:[{id:crypto.randomUUID(),item:'排水流量与水位关系比较',advice:''},{id:crypto.randomUUID(),item:'坑外水位观测',advice:''}]},plans:[],signatures:{authors:'',reviewers:'',approver:''},progress:Object.fromEntries(stages.map(([k])=>[k,'pending'])),currentStage:'basics',layout:{version:1,galleries:{}},chat:[],createdAt:new Date().toISOString()};}
export function validateReport(r:any){if(!r||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||isNaN(Date.parse(r.date+'T00:00:00Z'))||new Date(r.date+'T00:00:00Z').toISOString().slice(0,10)!==r.date)throw Error('日报日期无效。');if(!r||typeof r.id!=='string'||typeof r.title!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||!r.slots||!r.rich||!r.demolition||!r.drainage||!r.signatures||!r.progress||!Array.isArray(r.plans)||!Array.isArray(r.demolition.issues)||!Array.isArray(r.drainage.items))throw Error('日报格式不完整。');if(stages.some(([k])=>!['pending','confirmed'].includes(r.progress[k])))throw Error('日报阶段状态无效。');validateLayout(r);for(const k of Object.keys(r.rich)){if(!Array.isArray(r.rich[k])||r.rich[k].some((x:any)=>typeof x!=='object'||x===null||(x.text!==undefined&&typeof x.text!=='string')||(x.size!==undefined&&(!Number.isFinite(x.size)||x.size<6||x.size>48))||(x.color!==undefined&&!/^[a-f0-9]{6}$/i.test(x.color))||(x.bind!==undefined&&!['date_cn','slots.task','slots.work','slots.inspection','slots.completed','slots.water_level','slots.water_change'].includes(x.bind))))throw Error('日报文字格式无效。');}}
export function binding(r:any,key:string){if(key==='date_cn'){const [y,m,d]=r.date.split('-');return `${y}年${Number(m)}月${Number(d)}日`;}return key.split('.').reduce((o:any,k:string)=>o?.[k],r)??'';}
export function runs(r:any,key:string){if(['project','title','experts','signatures.authors','signatures.reviewers','signatures.approver'].includes(key))return [{text:String(binding(r,key)),size:key==='project'||key==='title'?18:14,bold:key==='project'||key==='title',color:'000000',font:'仿宋'}];return (r.rich[key]||[]).map((x:any)=>({...x,text:x.bind?String(binding(r,x.bind)):x.text||''}));}
export function reportText(r:any,key:string){return runs(r,key).map((x:any)=>x.text).join('');}
export function validateStage(r:any,stage:string){const required:Record<string,string[]>={basics:['project','weather','experts','slots.task'],demolition:['slots.work','slots.inspection','slots.completed'],drainage:['slots.water_level','slots.water_change'],signatures:['signatures.authors','signatures.reviewers','signatures.approver']};if((required[stage]||[]).some(k=>!String(binding(r,k)).trim()))throw Error('请填写本阶段的必要信息后再确认。');if(stage==='issues'){if(r.demolition.issuesEnabled&&(!r.demolition.issues.length||r.demolition.issues.some((x:any)=>!x.advice.trim()||!x.photos?.length)))throw Error('请为每条结构安全意见填写文字并添加现场照片；无需此表时请关闭“显示结构安全意见表”。');if(!reportText(r,'demolition.conclusion').trim())throw Error('请填写结构巡查结论。');}if(stage==='drainage_safety'){if(!r.drainage.items.length||r.drainage.items.some((x:any)=>!x.item.trim()||!x.advice.trim()))throw Error('请填写各条降排水安全事项与顾问意见。');if(!reportText(r,'drainage.conclusion').trim())throw Error('请填写降排水结论。');}if(stage==='plans'&&(!r.plans.length||r.plans.some((x:any)=>!x.text.trim())))throw Error('请填写次日工作计划。');}
