export const PT_PER_MM=72/25.4;
export function galleryPaths(r:any){return ['demolition.images','drainage.images','drainage.monitoring',...(r.demolition?.issues||[]).map((x:any)=>'demolition.issues.'+x.id+'.photos')];}
export function stablePath(r:any,path:string){const match=/^demolition\.issues\.(\d+)\.photos$/.exec(path);return match?'demolition.issues.'+(r.demolition.issues[Number(match[1])]?.id||match[1])+'.photos':path;}
export function galleryImages(r:any,path:string):any[]{if(path.startsWith('demolition.issues.'))return r.demolition.issues.find((x:any)=>x.id===path.split('.')[2])?.photos||[];const [a,b]=path.split('.');return r[a]?.[b]||[];}
export function setGalleryImages(r:any,path:string,images:any[]){if(path.startsWith('demolition.issues.')){const row=r.demolition.issues.find((x:any)=>x.id===path.split('.')[2]);if(!row)throw Error('对应意见行不存在。');row.photos=images;}else{const [a,b]=path.split('.');r[a][b]=images;}}
export function gallerySettings(r:any,path:string){return {columns:0,gapMm:3,...r.layout?.galleries?.[path]};}
export function imageSettings(r:any,path:string,image:any){return {widthPct:100,maxHeightMm:path==='drainage.images'?160:path.endsWith('.photos')?70:path==='demolition.images'?72:115,align:'center',breakBefore:false,ownPage:false,caption:image.caption||'',...(image.wide?{span:3}:{}),...r.layout?.galleries?.[path]?.items?.[image.id]};}
export function setGallerySetting(r:any,path:string,value:any){r.layout??={version:1,galleries:{},tables:{meta:{widths:[14,27,16,43]}}};r.layout.galleries??={};r.layout.galleries[path]={...r.layout.galleries[path],...value};}
export function setImageSetting(r:any,path:string,id:string,value:any){const g=gallerySettings(r,path);setGallerySetting(r,path,{items:{...g.items,[id]:{...g.items?.[id],...value}}});}
export function moveImage(r:any,source:string,destination:string,id:string,index?:number){const images=galleryImages(r,source),image=images.find(x=>x.id===id);if(!image)throw Error('图片已移除。');if(source!==destination&&galleryImages(r,destination).some(x=>x.id===id))throw Error('目标图库已经有这张图片。');const style={...r.layout?.galleries?.[source]?.items?.[id]};setGalleryImages(r,source,images.filter(x=>x.id!==id));const dest=[...galleryImages(r,destination)];const at=index??dest.length;if(!Number.isInteger(at)||at<0||at>dest.length)throw Error('图片顺序无效。');dest.splice(at,0,image);setGalleryImages(r,destination,dest);if(r.layout?.galleries?.[source]?.items)delete r.layout.galleries[source].items[id];if(destination.endsWith('.photos')){style.breakBefore=false;style.ownPage=false;}setImageSetting(r,destination,id,style);}
export function validateLayout(r:any){for(const path of galleryPaths(r)){const g=gallerySettings(r,path);if(!Number.isInteger(g.columns)||g.columns<0||g.columns>3||!Number.isFinite(g.gapMm)||g.gapMm<0||g.gapMm>10)throw Error('每行图片数须为0–3，间距须为0–10毫米。');for(const image of galleryImages(r,path)){const s=imageSettings(r,path,image);if(typeof s.breakBefore!=='boolean'||typeof s.ownPage!=='boolean'||path.endsWith('.photos')&&(s.breakBefore||s.ownPage))throw Error('表格照片不能单独分页；分页设置须为是或否。');if(!Number.isFinite(s.widthPct)||s.widthPct<20||s.widthPct>100||!Number.isFinite(s.maxHeightMm)||s.maxHeightMm<30||s.maxHeightMm>220||!['left','center','right'].includes(s.align)||s.span!=null&&(!Number.isInteger(s.span)||s.span<1||s.span>3)||typeof s.caption!=='string'||s.caption.length>300)throw Error('图片尺寸、对齐或图注设置无效。');}}}
export function planGallery(r:any,path:string,widthPt=415,dimensions:Record<string,{width:number;height:number}>={}){const images=galleryImages(r,path),g=gallerySettings(r,path),auto=g.columns===0;let columns=g.columns||(path==='drainage.images'||path.endsWith('.photos')?1:2);if(auto&&images.length===1)columns=1;const gapPt=Math.min(g.gapMm*PT_PER_MM,widthPt/(columns*4)),unit=(widthPt-gapPt*(columns-1))/columns,maxHeight=path.endsWith('.photos')?200:480,rows:any[]=[];let current:any[]=[],used=0;const flush=()=>{if(current.length)rows.push({heightPt:Math.max(...current.map(x=>x.heightPt)),columns,gapPt,breakBefore:current[0].breakBefore,breakAfter:current.some(x=>x.ownPage),items:current});current=[];used=0;};for(const im of images){const s=imageSettings(r,path,im),d=dimensions[im.id]||im,width=d.width||4,height=d.height||3,span=s.ownPage?columns:Math.min(columns,s.span??(auto&&width/height>=1.8?columns:1)),pageBreak=!path.endsWith('.photos')&&(s.breakBefore||s.ownPage);if(pageBreak||used+span>columns)flush();const cellWidthPt=unit*span+gapPt*(span-1),chars=Math.max(1,Math.floor(cellWidthPt/10)-1),captionLines=s.caption?s.caption.split('\n').reduce((n:number,line:string)=>n+Math.max(1,Math.ceil(line.length/chars)),0):0,captionHeight=captionLines?captionLines*15+6:0;if(captionHeight>maxHeight-30)throw Error('图注过长，请增加占列宽度或缩短图注。');const scale=Math.min(cellWidthPt*s.widthPct/100/width,Math.min(maxHeight-captionHeight,s.maxHeightMm*PT_PER_MM)/height);current.push({id:im.id,column:used,span,cellWidthPt,widthPt:width*scale,heightPt:height*scale,caption:s.caption,align:s.align,breakBefore:pageBreak,ownPage:!path.endsWith('.photos')&&s.ownPage});used+=span;if(used===columns)flush();}flush();return rows;}
